/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Help.Clock;
import Model.Nhanvien;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class MainGui extends javax.swing.JFrame {

    static Nhanvien _nhanvien = new Nhanvien();
    NguoihocGui nguoihocGUI = new NguoihocGui();
    ChuyendeGUI chuyendeGUI = new ChuyendeGUI();
    KhoaHocGUI khoaHoc = new KhoaHocGUI();
    NhavienGUI nhanvien = new NhavienGUI();

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("QUẢN LÝ ĐÀO TẠO");
        JLabel lblClock = new JLabel("New label");
        lblClock.setBounds(640, 0, 95, 24);
        pn_dh.add(lblClock);
        Clock clock = new Clock(lblClock);
        clock.start();
        seticon();
    }

    void seticon() {
        btn_out.setIcon(new ImageIcon("img/dangxuat1.png"));
        btn_end.setIcon(new ImageIcon("img/ketthuc1.png"));
        btn_CD.setIcon(new ImageIcon("img/chuyende1.png"));
        btn_DH.setIcon(new ImageIcon("img/hdsd.png"));
        btn_HV.setIcon(new ImageIcon("img/hocvien1.png"));
        btn_NH.setIcon(new ImageIcon("img/nguoihoc1.png"));
        btn_KH.setIcon(new ImageIcon("img/khoahoc1.png"));
        lbl_clock.setIcon(new ImageIcon("img/clock.png"));
    }

    public static Nhanvien getNv(Nhanvien x) {
        _nhanvien = x;
        return x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        tb_menu = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btn_out = new javax.swing.JButton();
        btn_end = new javax.swing.JButton();
        btn_CD = new javax.swing.JButton();
        btn_NH = new javax.swing.JButton();
        btn_KH = new javax.swing.JButton();
        btn_HV = new javax.swing.JButton();
        btn_DH = new javax.swing.JButton();
        pn_dh = new javax.swing.JPanel();
        lbl_clock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destopane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuBd = new javax.swing.JMenu();
        mnBangdiem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnNH = new javax.swing.JMenuItem();
        mndiemCD = new javax.swing.JMenuItem();
        mnDoanhthu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnBangdiem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_menu.setRollover(true);

        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tb_menu.add(jButton1);

        btn_out.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_out.setText("Đăng xuất");
        btn_out.setFocusable(false);
        btn_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_out.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });
        tb_menu.add(btn_out);

        btn_end.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_end.setText("Kết thúc");
        btn_end.setFocusable(false);
        btn_end.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_end.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endActionPerformed(evt);
            }
        });
        tb_menu.add(btn_end);

        btn_CD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_CD.setText("Chuyên đề");
        btn_CD.setFocusable(false);
        btn_CD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_CD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CDActionPerformed(evt);
            }
        });
        tb_menu.add(btn_CD);

        btn_NH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_NH.setText("Người học");
        btn_NH.setFocusable(false);
        btn_NH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_NH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_NH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NHActionPerformed(evt);
            }
        });
        tb_menu.add(btn_NH);

        btn_KH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_KH.setText("Khóa học");
        btn_KH.setFocusable(false);
        btn_KH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_KH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KHActionPerformed(evt);
            }
        });
        tb_menu.add(btn_KH);

        btn_HV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_HV.setText("Học viên");
        btn_HV.setFocusable(false);
        btn_HV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_HV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_HV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HVActionPerformed(evt);
            }
        });
        tb_menu.add(btn_HV);

        btn_DH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_DH.setText("Hướng dẫn");
        btn_DH.setFocusable(false);
        btn_DH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DHActionPerformed(evt);
            }
        });
        tb_menu.add(btn_DH);

        getContentPane().add(tb_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 49));

        pn_dh.add(lbl_clock);

        getContentPane().add(pn_dh, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\hoc tap\\DUANMAU\\DA\\img\\trogiup2.png")); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 160, -1));
        getContentPane().add(destopane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, 510));

        jMenu1.setText("Hệ thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Đăng nhập");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Đăng xuất");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem7MouseClicked(evt);
            }
        });
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setText("Kết thúc");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem8MouseClicked(evt);
            }
        });
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        jMenu5.setText("Quản lý nhân viên");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Quản lý chuyên đề");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Quản lý khóa học");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Quản lý người học");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Quản lý học viên");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        menuBd.setText("Thống kê");
        menuBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBdActionPerformed(evt);
            }
        });

        mnBangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnBangdiem.setText("Bảng điểm");
        mnBangdiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnBangdiemMouseClicked(evt);
            }
        });
        mnBangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBangdiemActionPerformed(evt);
            }
        });
        menuBd.add(mnBangdiem);
        menuBd.add(jSeparator1);

        mnNH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnNH.setText("Lượng người học");
        mnNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnNHMouseClicked(evt);
            }
        });
        mnNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNHActionPerformed(evt);
            }
        });
        menuBd.add(mnNH);

        mndiemCD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mndiemCD.setText("Điểm chuyên đề");
        mndiemCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mndiemCDMouseClicked(evt);
            }
        });
        mndiemCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndiemCDActionPerformed(evt);
            }
        });
        menuBd.add(mndiemCD);

        mnDoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnDoanhthu.setText("Doanh thu");
        mnDoanhthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDoanhthuMouseClicked(evt);
            }
        });
        mnDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoanhthuActionPerformed(evt);
            }
        });
        menuBd.add(mnDoanhthu);

        jMenuBar1.add(menuBd);

        jMenu4.setText("Trợ giúp");

        mnBangdiem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnBangdiem1.setText("Đổi mật khẩu");
        mnBangdiem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnBangdiem1MouseClicked(evt);
            }
        });
        mnBangdiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBangdiem1ActionPerformed(evt);
            }
        });
        jMenu4.add(mnBangdiem1);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setText("Hướng dẫn sử dựng");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem9MouseClicked(evt);
            }
        });
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Giới thiệu sản phẩm");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseClicked(evt);
            }
        });
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        new LoginGui().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_outActionPerformed

    private void btn_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_endActionPerformed

    private void btn_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CDActionPerformed
        try {

            ChuyendeGUI.getNV(_nhanvien);
            destopane.add(chuyendeGUI);
            chuyendeGUI.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_CDActionPerformed

    private void btn_NHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NHActionPerformed

        try {
            destopane.add(nguoihocGUI);
            NguoihocGui.nvlogin(_nhanvien);
            nguoihocGUI.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_NHActionPerformed

    private void btn_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KHActionPerformed
        try {
            KhoaHocGUI.getnvlog(_nhanvien);
            destopane.add(khoaHoc);
            khoaHoc.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_KHActionPerformed

    private void btn_HVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HVActionPerformed
        // TODO add your handling code here:
        HocvienGUI hgui = new HocvienGUI();
        destopane.add(hgui);
        hgui.setVisible(true);
    }//GEN-LAST:event_btn_HVActionPerformed

    private void btn_DHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DHActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "duy dzai");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        try {
            if (_nhanvien.getChucvu() == 1) {
                NhavienGUI.nvlogin(_nhanvien);
                destopane.add(nhanvien);
                nhanvien.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(destopane, "Bạn không có quyền vào mục này");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void menuBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBdActionPerformed

    private void mnBangdiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnBangdiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnBangdiemMouseClicked

    private void mnBangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBangdiemActionPerformed
        // TODO add your handling code here:
        ThongkeGUI.getNV(_nhanvien);
        ThongkeGUI.getindextab(0);
        ThongkeGUI tk = new ThongkeGUI();
        destopane.add(tk);
        tk.setVisible(true);
    }//GEN-LAST:event_mnBangdiemActionPerformed

    private void mnNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnNHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnNHMouseClicked

    private void mnNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNHActionPerformed
        // TODO add your handling code here:
                ThongkeGUI.getNV(_nhanvien);
        ThongkeGUI tk = new ThongkeGUI();
        tk.setVisible(true);
        ThongkeGUI.getindextab(1);
    }//GEN-LAST:event_mnNHActionPerformed

    private void mndiemCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mndiemCDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mndiemCDMouseClicked

    private void mndiemCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndiemCDActionPerformed
        // TODO add your handling code here:
        ThongkeGUI.getNV(_nhanvien);
        ThongkeGUI tk = new ThongkeGUI();
        tk.setVisible(true);
        ThongkeGUI.getindextab(2);
    }//GEN-LAST:event_mndiemCDActionPerformed

    private void mnDoanhthuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDoanhthuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnDoanhthuMouseClicked

    private void mnDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoanhthuActionPerformed
        // TODO add your handling code here:
        if (_nhanvien.getChucvu() == 1) {
            ThongkeGUI.getNV(_nhanvien);
            ThongkeGUI tk = new ThongkeGUI();
            tk.setVisible(true);
            ThongkeGUI.getindextab(3);
        } else {
            JOptionPane.showMessageDialog(destopane, "Bạn không được quyền truy cập mục này");
        }
    }//GEN-LAST:event_mnDoanhthuActionPerformed

    private void mnBangdiem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnBangdiem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnBangdiem1MouseClicked

    private void mnBangdiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBangdiem1ActionPerformed
        // TODO add your handling code here:
        doipass.getnhanvien(_nhanvien);
        doipass x = new doipass();
        destopane.add(x);
        x.setVisible(true);
    }//GEN-LAST:event_mnBangdiem1ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8MouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        openweb("https://lms.poly.edu.vn/");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        openweb("https://lms.poly.edu.vn/");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CD;
    private javax.swing.JButton btn_DH;
    private javax.swing.JButton btn_HV;
    private javax.swing.JButton btn_KH;
    private javax.swing.JButton btn_NH;
    private javax.swing.JButton btn_end;
    private javax.swing.JButton btn_out;
    private javax.swing.JDesktopPane destopane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_clock;
    private javax.swing.JMenu menuBd;
    private javax.swing.JMenuItem mnBangdiem;
    private javax.swing.JMenuItem mnBangdiem1;
    private javax.swing.JMenuItem mnDoanhthu;
    private javax.swing.JMenuItem mnNH;
    private javax.swing.JMenuItem mndiemCD;
    private javax.swing.JPanel pn_dh;
    private javax.swing.JToolBar tb_menu;
    // End of variables declaration//GEN-END:variables

    private void openweb(String url) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(new URI(url));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
